
    alter table Translation 
        drop 
        foreign key FKF5B39A9121237D2C;

    alter table Translation 
        drop 
        foreign key FKF5B39A91B2B40028;

    alter table Translation 
        drop 
        foreign key FKF5B39A91401B820C;

    alter table Translation 
        drop 
        foreign key FKF5B39A918B3B54E8;

    alter table authorities 
        drop 
        foreign key FK2B0F13219D90DDE5;

rename table authorities to tmp_authorities;
rename table AuditLogRecord to tmp_AuditLogRecord;
rename table Bundle to tmp_Bundle;
rename table Country to tmp_Country;
rename table Keyword to tmp_Keyword;
rename table Language to tmp_Language;
rename table ServerData to tmp_ServerData;
rename table Translation to tmp_Translation;
rename table User to tmp_User;



    alter table authorities 
        drop constraint fk_internal_user_authorities;

    alter table translation 
        drop constraint fk_keyword_translation;

    alter table translation 
        drop constraint fk_bundle_translation;

    alter table translation 
        drop constraint fk_country_translation;

    alter table translation 
        drop constraint fk_language_translation;

    drop table audit_log_record if exists;

    drop table authorities if exists;

    drop table bundle if exists;

    drop table country if exists;

    drop table internal_user if exists;

    drop table keyword if exists;

    drop table language if exists;

    drop table server_data if exists;

    drop table translation if exists;

    create table audit_log_record (
        audit_log_record_id bigint generated by default as identity (start with 1),
        created timestamp not null,
        entity_class varchar(255) not null,
        entity_id bigint not null,
        message varchar(7) not null,
        new_value longvarchar,
        old_value longvarchar,
        username varchar(255),
        primary key (audit_log_record_id)
    );

    create table authorities (
        user_id bigint not null,
        permission varchar(13) not null,
        primary key (user_id, permission)
    );

    create table bundle (
        bundle_id bigint generated by default as identity (start with 1),
        description varchar(255),
        is_default bit not null,
        is_global bit not null,
        name varchar(255) not null,
        resource_name varchar(255) not null,
        primary key (bundle_id),
        unique (resource_name),
        unique (name)
    );

    create table country (
        country_id bigint generated by default as identity (start with 1),
        code varchar(7) not null,
        name varchar(255) not null,
        primary key (country_id),
        unique (code)
    );

    create table internal_user (
        internal_user_id bigint generated by default as identity (start with 1),
        account_non_expired bit not null,
        account_non_locked bit not null,
        credentials_non_expired bit not null,
        email varchar(255) not null,
        enabled bit not null,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        password varchar(255) not null,
        username varchar(255) not null,
        optlock integer,
        primary key (internal_user_id),
        unique (username)
    );

    create table keyword (
        keyword_id bigint generated by default as identity (start with 1),
        context longvarchar,
        keyword varchar(255) not null,
        optlock integer,
        primary key (keyword_id),
        unique (keyword)
    );

    create table language (
        language_id bigint generated by default as identity (start with 1),
        code varchar(7) not null,
        name varchar(255) not null,
        primary key (language_id),
        unique (code)
    );

    create table server_data (
        server_data_id bigint generated by default as identity (start with 1),
        build_date timestamp not null,
        build_number varchar(10) not null,
        setup_date timestamp not null,
        version varchar(10) not null,
        primary key (server_data_id),
        unique (version, build_number)
    );

    create table translation (
        translation_id bigint generated by default as identity (start with 1),
        state varchar(10) not null,
        value longvarchar,
        optlock integer,
        bundle_id bigint,
        country_id bigint,
        keyword_id bigint,
        language_id bigint,
        primary key (translation_id),
        unique (keyword_id, language_id, country_id, bundle_id)
    );

    alter table authorities 
        add constraint fk_internal_user_authorities 
        foreign key (user_id) 
        references internal_user;

    alter table translation 
        add constraint fk_keyword_translation 
        foreign key (keyword_id) 
        references keyword;

    alter table translation 
        add constraint fk_bundle_translation 
        foreign key (bundle_id) 
        references bundle;

    alter table translation 
        add constraint fk_country_translation 
        foreign key (country_id) 
        references country;

    alter table translation 
        add constraint fk_language_translation 
        foreign key (language_id) 
        references language;

insert into server_data(build_date, build_number, setup_date, version)
    select buildDate, buildNumber, setupDate, version from tmp_ServerData;
insert into bundle(description, is_default, is_global, name, resource_name)
    select description, isDefault, isGlobal, name, resourceName from tmp_Bundle;
insert into country select * from tmp_Country;
insert into language select * from tmp_Language;
insert into keyword(context, keyword, OPTLOCK)
    select context, keyword, optlock from tmp_Keyword;
insert into translation(state, value, optlock, bundle_id, country_id, keyword_id, language_id)
    select state, value, OPTLOCK, 
            (select b.bundle_id from bundle b, tmp_Bundle tmpBundle where t.BUNDLE_ID = tmpBundle.id and b.name = tmpBundle.name),
            (select c.country_id from country c, tmp_Country tmpCountry where t.COUNTRY_ID = tmpCountry.id and c.name = tmpCountry.name),
            (select k.keyword_id from keyword k, tmp_Keyword tmpKeyword where t.KEYWORD_ID = tmpKeyword.id and k.keyword = tmpKeyword.keyword),
            (select l.language_id from language l, tmp_Language tmpLanguage where t.LANGUAGE_ID = tmpLanguage.id and l.name = tmpLanguage.name)
    from tmp_Translation t;
insert into audit_log_record(created, entity_class, entity_id, message, new_value, old_value, username)
    select created, entityClass, entityId, message, null, null, username from tmp_AuditLogRecord;
update audit_log_record
set message = 'insert'
where message = 'new';
insert into internal_user(account_non_expired, account_non_locked, credentials_non_expired, email, enabled, first_name, last_name, password, username, optlock)
    select accountNonExpired, accountNonLocked, credentialsNonExpired, email, enabled, firstName, lastName, password, username, OPTLOCK from tmp_User;
insert into authorities(user_id, permission)
    select u.internal_user_id, a.permission 
    from tmp_authorities a, tmp_User tmpUser, internal_user u
    where a.userid = tmpUser.id
    and tmpUser.username = u.username;

drop table if exists tmp_Translation cascade;
drop table if exists tmp_AuditLogRecord cascade;
drop table if exists tmp_Keyword cascade;
drop table if exists tmp_Language cascade;
drop table if exists tmp_Bundle cascade;
drop table if exists tmp_Country cascade;
drop table if exists tmp_ServerData cascade;
drop table if exists tmp_authorities cascade;
drop table if exists tmp_User cascade;

commit;

