
    alter table authorities 
        drop constraint fk_internal_user_authorities;

    alter table translation 
        drop constraint fk_keyword_translation;

    alter table translation 
        drop constraint fk_bundle_translation;

    alter table translation 
        drop constraint fk_country_translation;

    alter table translation 
        drop constraint fk_language_translation;

    drop table audit_log_record if exists;

    drop table authorities if exists;

    drop table bundle if exists;

    drop table country if exists;

    drop table internal_user if exists;

    drop table keyword if exists;

    drop table language if exists;

    drop table server_data if exists;

    drop table translation if exists;

    create table audit_log_record (
        audit_log_record_id bigint generated by default as identity (start with 1),
        created timestamp not null,
        entity_class varchar(255) not null,
        entity_id bigint not null,
        message varchar(7) not null,
        new_value longvarchar,
        old_value longvarchar,
        username varchar(255),
        primary key (audit_log_record_id)
    );

    create table authorities (
        user_id bigint not null,
        permission varchar(13) not null,
        primary key (user_id, permission)
    );

    create table bundle (
        bundle_id bigint generated by default as identity (start with 1),
        description varchar(255),
        is_default bit not null,
        is_global bit not null,
        name varchar(255) not null,
        resource_name varchar(255) not null,
        primary key (bundle_id),
        unique (resource_name),
        unique (name)
    );

    create table country (
        country_id bigint generated by default as identity (start with 1),
        code varchar(7) not null,
        name varchar(255) not null,
        primary key (country_id),
        unique (code)
    );

    create table internal_user (
        internal_user_id bigint generated by default as identity (start with 1),
        account_non_expired bit not null,
        account_non_locked bit not null,
        credentials_non_expired bit not null,
        email varchar(255) not null,
        enabled bit not null,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        password varchar(255) not null,
        username varchar(255) not null,
        optlock integer,
        primary key (internal_user_id),
        unique (username)
    );

    create table keyword (
        keyword_id bigint generated by default as identity (start with 1),
        context longvarchar,
        keyword varchar(255) not null,
        optlock integer,
        primary key (keyword_id),
        unique (keyword)
    );

    create table language (
        language_id bigint generated by default as identity (start with 1),
        code varchar(7) not null,
        name varchar(255) not null,
        primary key (language_id),
        unique (code)
    );

    create table server_data (
        server_data_id bigint generated by default as identity (start with 1),
        build_date timestamp not null,
        build_number varchar(10) not null,
        setup_date timestamp not null,
        version varchar(10) not null,
        primary key (server_data_id),
        unique (version, build_number)
    );

    create table translation (
        translation_id bigint generated by default as identity (start with 1),
        state varchar(10) not null,
        value longvarchar,
        optlock integer,
        bundle_id bigint,
        country_id bigint,
        keyword_id bigint,
        language_id bigint,
        primary key (translation_id),
        unique (keyword_id, language_id, country_id, bundle_id)
    );

    alter table authorities 
        add constraint fk_internal_user_authorities 
        foreign key (user_id) 
        references internal_user;

    alter table translation 
        add constraint fk_keyword_translation 
        foreign key (keyword_id) 
        references keyword;

    alter table translation 
        add constraint fk_bundle_translation 
        foreign key (bundle_id) 
        references bundle;

    alter table translation 
        add constraint fk_country_translation 
        foreign key (country_id) 
        references country;

    alter table translation 
        add constraint fk_language_translation 
        foreign key (language_id) 
        references language;
